services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: phpgio-app
    restart: always
    working_dir: /var/www
    volumes:
      - ../src:/var/www
    ports:
      - "9000:9000"  # Expose port 9000 for PHP-FPM

  nginx:
    image: nginx:1.19-alpine
    container_name: phpgio-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d